# Generated by Django 6.0.2 on 2026-03-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('driver', 'Driver'), ('conductor', 'Conductor'), ('pickup', 'Pickup (Delivery)'), ('branch_agent', 'Branch Agent')], default='branch_agent', max_length=20),
        ),
    ]
