"""
Django settings for shabiby_cargo_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Frontend dist folder path
FRONTEND_DIR = os.path.join(BASE_DIR.parent, 'shabiby_cargo_frontend', 'dist')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lsyho6k!eg2omq#q9-$3tnkg%rc0d$cp&gfdmw$wvr#9$!#!5+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'test.gdenceinvestments.co.tz',
    '.ngrok-free.app',
    '.ngrok.io',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'corsheaders',
    'auths',
    'admin',
    'cargo_management',
    'conductor',
    'branch_agent',
    'homepage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shabiby_cargo_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            FRONTEND_DIR,
            os.path.join(BASE_DIR, 'admin', 'templates'),
            os.path.join(BASE_DIR, 'branch_agent', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'shabiby_cargo_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'cargodb'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(FRONTEND_DIR, 'static')

# Additional locations of static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Assets folder for Vite build output
ASSETS_ROOT = os.path.join(FRONTEND_DIR, 'assets')

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'auths.User'

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
}

# PWA Configuration - DISABLED
# PWA_APP_NAME = 'Shabiby Cargo'
# PWA_APP_SHORT_NAME = 'Shabiby'
# PWA_APP_DESCRIPTION = 'Shabiby Cargo Management System - Track and manage cargo shipments'
# PWA_APP_THEME_COLOR = '#4680ff'
# PWA_APP_BACKGROUND_COLOR = '#ffffff'
# PWA_APP_DISPLAY = 'standalone'
# PWA_APP_SCOPE = '/'
# PWA_APP_ORIENTATION = 'portrait-primary'
# PWA_APP_START_URL = '/'
# PWA_APP_STATUS_BAR_COLOR = 'default'

# PWA_APP_ICONS = [
#     {
#         'src': '/static/icons/icon-72x72.png',
#         'sizes': '72x72',
#         'type': 'image/png',
#         'purpose': 'any maskable'
#     },
#     {
#         'src': '/static/icons/icon-96x96.png',
#         'sizes': '96x96',
#         'type': 'image/png',
#         'purpose': 'any maskable'
#     },
#     {
#         'src': '/static/icons/icon-128x128.png',
#         'sizes': '128x128',
#         'type': 'image/png',
#         'purpose': 'any maskable'
#     },
#     {
#         'src': '/static/icons/icon-144x144.png',
#         'sizes': '144x144',
#         'type': 'image/png',
#         'purpose': 'any maskable'
#     },
#     {
#         'src': '/static/icons/icon-152x152.png',
#         'sizes': '152x152',
#         'type': 'image/png',
#         'purpose': 'any maskable'
#     },
#     {
#         'src': '/static/icons/icon-192x192.png',
#         'sizes': '192x192',
#         'type': 'image/png',
#         'purpose': 'any maskable'
#     },
#     {
#         'src': '/static/icons/icon-384x384.png',
#         'sizes': '384x384',
#         'type': 'image/png',
#         'purpose': 'any maskable'
#     },
#     {
#         'src': '/static/icons/icon-512x512.png',
#         'sizes': '512x512',
#         'type': 'image/png',
#         'purpose': 'any maskable'
#     }
# ]

# PWA_APP_ICONS_APPLE = [
#     {
#         'src': '/static/icons/icon-152x152.png',
#         'sizes': '152x152'
#     }
# ]

# PWA_APP_SPLASH_SCREEN = [
#     {
#         'src': '/static/icons/icon-512x512.png',
#         'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
#     }
# ]

# PWA_APP_DIR = 'ltr'
# PWA_APP_LANG = 'en-US'
# PWA_SERVICE_WORKER_PATH = BASE_DIR / 'static' / 'serviceworker.js'

# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://test.gdenceinvestments.co.tz',
    'https://*.ngrok-free.app',
    'https://*.ngrok.io',
    'http://*.ngrok-free.app',
    'http://*.ngrok.io',
]


