# Generated by Django 6.0.2 on 2026-03-14 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('branch_code', models.CharField(help_text='3-letter branch code (e.g., DAR, DOD, MWA)', max_length=3, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cargo Center',
                'verbose_name_plural': 'Cargo Centers',
                'db_table': 'cargo_centers',
                'ordering': ['location', 'center_name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cargo_value', models.DecimalField(decimal_places=2, help_text='Minimum cargo value for this fee range', max_digits=12)),
                ('max_cargo_value', models.DecimalField(decimal_places=2, help_text='Maximum cargo value for this fee range', max_digits=12)),
                ('shipping_fee', models.DecimalField(decimal_places=2, help_text='Shipping fee for this cargo value range', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Fee Configuration',
                'verbose_name_plural': 'Shipping Fee Configurations',
                'db_table': 'shipping_fee_configs',
                'ordering': ['min_cargo_value'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('bus', 'Bus'), ('car', 'Car'), ('van', 'Van'), ('pickup', 'Pickup'), ('trailer', 'Trailer'), ('motorcycle', 'Motorcycle')], help_text='Type of vehicle', max_length=20)),
                ('vehicle_model', models.CharField(help_text='Vehicle model (e.g., Toyota Hilux, Isuzu FRR)', max_length=100)),
                ('company_owner', models.CharField(help_text='Company or owner name', max_length=200)),
                ('registration_number', models.CharField(help_text='Vehicle registration number', max_length=50, unique=True)),
                ('plate_number', models.CharField(help_text='Vehicle plate number', max_length=20, unique=True)),
                ('max_weight', models.DecimalField(decimal_places=2, help_text='Maximum weight capacity in tons', max_digits=6)),
                ('chassis_number', models.CharField(blank=True, help_text='Vehicle chassis number (optional)', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the vehicle is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='cargo_management.cargocenter')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'db_table': 'agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_number', models.CharField(blank=True, help_text='Cargo/Parcel number (e.g., SHB03082026-64678D)', max_length=50, null=True, unique=True)),
                ('tracking_number', models.CharField(blank=True, help_text='Tracking ID (6 mixed characters)', max_length=10, null=True, unique=True)),
                ('cargo_description', models.TextField(help_text='Description of the cargo')),
                ('cargo_value', models.DecimalField(decimal_places=2, help_text='Declared value of the cargo', max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of items/packages')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight of cargo in kilograms', max_digits=8, null=True)),
                ('cargo_image', models.ImageField(blank=True, help_text='Photo/image of the cargo', null=True, upload_to='cargo_images/')),
                ('shipping_amount', models.DecimalField(decimal_places=2, help_text='Amount charged for shipping', max_digits=10)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('shipped', 'Shipped (On Way)'), ('arrived', 'Arrival at Branch'), ('delivered', 'Taken by Customer')], default='registered', help_text='Current status of the cargo', max_length=20)),
                ('receipt_number', models.CharField(blank=True, help_text='Unique receipt number for thermal printer', max_length=50, null=True, unique=True)),
                ('pickup_customer_name', models.CharField(blank=True, help_text='Name of person who picked up the cargo', max_length=200, null=True)),
                ('pickup_customer_mobile', models.CharField(blank=True, help_text='Mobile number of person who picked up the cargo', max_length=20, null=True)),
                ('pickup_customer_location', models.CharField(blank=True, help_text='Location/address of person who picked up the cargo', max_length=200, null=True)),
                ('delivery_signature', models.TextField(blank=True, help_text='Base64 encoded signature of person who picked up the cargo', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_by_agent', models.ForeignKey(blank=True, help_text='Agent who handed over the cargo to customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_cargos', to='cargo_management.agent')),
                ('registered_by', models.ForeignKey(blank=True, help_text='Agent who registered this cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_cargos', to='cargo_management.agent')),
                ('shipped_by', models.ForeignKey(blank=True, help_text='Conductor/Agent who shipped this cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipped_cargos', to='cargo_management.agent')),
                ('current_branch', models.ForeignKey(blank=True, help_text='Current location of the cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_cargos', to='cargo_management.cargocenter')),
                ('destination_branch', models.ForeignKey(help_text='Branch where cargo will be delivered', on_delete=django.db.models.deletion.PROTECT, related_name='destination_cargos', to='cargo_management.cargocenter')),
                ('origin_branch', models.ForeignKey(help_text='Branch where cargo was registered', on_delete=django.db.models.deletion.PROTECT, related_name='origin_cargos', to='cargo_management.cargocenter')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CargoGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(help_text='Unique group identifier', max_length=50, unique=True)),
                ('qr_code_data', models.TextField(help_text='QR code data for scanning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Onboard'), ('onboarded', 'Onboarded'), ('offboarded', 'Offboarded')], default='pending', max_length=20)),
                ('onboarded_at', models.DateTimeField(blank=True, null=True)),
                ('offboarded_at', models.DateTimeField(blank=True, null=True)),
                ('cargos', models.ManyToManyField(help_text='Cargos in this group', related_name='cargo_groups', to='cargo_management.cargo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cargo_groups', to=settings.AUTH_USER_MODEL)),
                ('offboarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboarded_cargo_groups', to=settings.AUTH_USER_MODEL)),
                ('onboarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarded_cargo_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cargo Group',
                'verbose_name_plural': 'Cargo Groups',
                'db_table': 'cargo_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Customer's full name", max_length=200)),
                ('mobile_number', models.CharField(help_text="Customer's mobile number", max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, help_text="Customer's branch/location", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='cargo_management.cargocenter')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='receiver',
            field=models.ForeignKey(help_text='Customer receiving the cargo', on_delete=django.db.models.deletion.PROTECT, related_name='received_cargos', to='cargo_management.customer'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='sender',
            field=models.ForeignKey(help_text='Customer sending the cargo', on_delete=django.db.models.deletion.PROTECT, related_name='sent_cargos', to='cargo_management.customer'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, help_text='Vehicle assigned for transportation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cargos', to='cargo_management.vehicle'),
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_kg', models.DecimalField(decimal_places=2, help_text='Shipping rate per kilogram', max_digits=10)),
                ('base_rate', models.DecimalField(decimal_places=2, default=0, help_text='Base/minimum shipping rate', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rate is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_branch', models.ForeignKey(help_text='Destination branch', on_delete=django.db.models.deletion.CASCADE, related_name='destination_rates', to='cargo_management.cargocenter')),
                ('origin_branch', models.ForeignKey(help_text='Origin branch', on_delete=django.db.models.deletion.CASCADE, related_name='origin_rates', to='cargo_management.cargocenter')),
            ],
            options={
                'verbose_name': 'Shipping Rate',
                'verbose_name_plural': 'Shipping Rates',
                'db_table': 'shipping_rates',
                'ordering': ['origin_branch', 'destination_branch'],
                'unique_together': {('origin_branch', 'destination_branch')},
            },
        ),
    ]
