# Generated by Django 6.0.2 on 2026-03-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='registration_number',
        ),
    ]
