# Generated by Django 6.0.2 on 2026-03-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('bus', 'Bus'), ('car', 'Car'), ('van', 'Van'), ('pickup', 'Pickup'), ('trailer', 'Trailer'), ('motorcycle', 'Motorcycle')], help_text='Type of vehicle', max_length=20)),
                ('vehicle_model', models.CharField(help_text='Vehicle model (e.g., Toyota Hilux, Isuzu FRR)', max_length=100)),
                ('company_owner', models.CharField(help_text='Company or owner name', max_length=200)),
                ('registration_number', models.CharField(help_text='Vehicle registration number', max_length=50, unique=True)),
                ('plate_number', models.CharField(help_text='Vehicle plate number', max_length=20, unique=True)),
                ('max_weight', models.DecimalField(decimal_places=2, help_text='Maximum weight capacity in tons', max_digits=6)),
                ('chassis_number', models.CharField(blank=True, help_text='Vehicle chassis number (optional)', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the vehicle is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
