# Generated by Django 6.0.2 on 2026-03-08 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_management', '0002_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Customer's full name", max_length=200)),
                ('mobile_number', models.CharField(help_text="Customer's mobile number", max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, help_text="Customer's branch/location", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='cargo_management.cargocenter')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_description', models.TextField(help_text='Description of the cargo')),
                ('cargo_value', models.DecimalField(decimal_places=2, help_text='Declared value of the cargo', max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of items/packages')),
                ('shipping_amount', models.DecimalField(decimal_places=2, help_text='Amount charged for shipping', max_digits=10)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('shipped', 'Shipped (On Way)'), ('arrived', 'Arrival at Branch'), ('delivered', 'Taken by Customer')], default='registered', help_text='Current status of the cargo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_vehicle', models.ForeignKey(blank=True, help_text='Vehicle assigned for transportation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cargos', to='cargo_management.vehicle')),
                ('current_branch', models.ForeignKey(blank=True, help_text='Current location of the cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_cargos', to='cargo_management.cargocenter')),
                ('destination_branch', models.ForeignKey(help_text='Branch where cargo will be delivered', on_delete=django.db.models.deletion.PROTECT, related_name='destination_cargos', to='cargo_management.cargocenter')),
                ('origin_branch', models.ForeignKey(help_text='Branch where cargo was registered', on_delete=django.db.models.deletion.PROTECT, related_name='origin_cargos', to='cargo_management.cargocenter')),
                ('registered_by', models.ForeignKey(blank=True, help_text='Agent who registered this cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_cargos', to='cargo_management.agent')),
                ('receiver', models.ForeignKey(help_text='Customer receiving the cargo', on_delete=django.db.models.deletion.PROTECT, related_name='received_cargos', to='cargo_management.customer')),
                ('sender', models.ForeignKey(help_text='Customer sending the cargo', on_delete=django.db.models.deletion.PROTECT, related_name='sent_cargos', to='cargo_management.customer')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargos',
                'ordering': ['-created_at'],
            },
        ),
    ]
