# Generated by Django 6.0.2 on 2026-03-08 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_management', '0003_customer_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_kg', models.DecimalField(decimal_places=2, help_text='Shipping rate per kilogram', max_digits=10)),
                ('base_rate', models.DecimalField(decimal_places=2, default=0, help_text='Base/minimum shipping rate', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rate is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_branch', models.ForeignKey(help_text='Destination branch', on_delete=django.db.models.deletion.CASCADE, related_name='destination_rates', to='cargo_management.cargocenter')),
                ('origin_branch', models.ForeignKey(help_text='Origin branch', on_delete=django.db.models.deletion.CASCADE, related_name='origin_rates', to='cargo_management.cargocenter')),
            ],
            options={
                'verbose_name': 'Shipping Rate',
                'verbose_name_plural': 'Shipping Rates',
                'db_table': 'shipping_rates',
                'ordering': ['origin_branch', 'destination_branch'],
                'unique_together': {('origin_branch', 'destination_branch')},
            },
        ),
    ]
