# Generated by Django 6.0.2 on 2026-03-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_management', '0004_shippingrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='cargo_number',
            field=models.CharField(blank=True, help_text='Cargo/Parcel number (e.g., SHB03082026-64678D)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Tracking ID (6 mixed characters)', max_length=10, null=True, unique=True),
        ),
    ]
