# Generated by Django 6.0.2 on 2026-03-09 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_management', '0005_cargo_cargo_number_cargo_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='shipped_by',
            field=models.ForeignKey(blank=True, help_text='Conductor/Agent who shipped this cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipped_cargos', to='cargo_management.agent'),
        ),
    ]
