# Generated by Django 6.0.2 on 2026-03-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_management', '0006_cargo_shipped_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Unique receipt number for thermal printer', max_length=50, null=True, unique=True),
        ),
    ]
