# Generated by Django 6.0.2 on 2026-03-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_management', '0007_cargo_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of cargo in kilograms', max_digits=8, null=True),
        ),
    ]
