# Generated by Django 6.0.2 on 2026-03-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_management', '0008_cargo_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cargo_value', models.DecimalField(decimal_places=2, help_text='Minimum cargo value for this fee range', max_digits=12)),
                ('max_cargo_value', models.DecimalField(decimal_places=2, help_text='Maximum cargo value for this fee range', max_digits=12)),
                ('shipping_fee', models.DecimalField(decimal_places=2, help_text='Shipping fee for this cargo value range', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Fee Configuration',
                'verbose_name_plural': 'Shipping Fee Configurations',
                'db_table': 'shipping_fee_configs',
                'ordering': ['min_cargo_value'],
            },
        ),
    ]
