# Generated by Django 6.0.2 on 2026-03-12 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_management', '0009_shippingfeeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='delivered_by_agent',
            field=models.ForeignKey(blank=True, help_text='Agent who handed over the cargo to customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_cargos', to='cargo_management.agent'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='delivery_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded signature of person who picked up the cargo', null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pickup_customer_location',
            field=models.CharField(blank=True, help_text='Location/address of person who picked up the cargo', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pickup_customer_mobile',
            field=models.CharField(blank=True, help_text='Mobile number of person who picked up the cargo', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='pickup_customer_name',
            field=models.CharField(blank=True, help_text='Name of person who picked up the cargo', max_length=200, null=True),
        ),
    ]
